name: IKUUU-Auto-Checkin

on:
  workflow_dispatch:
  schedule:
    # UTC
    - cron: "1 43 * * *"

jobs:
  checkin:
    name: Checkin
    runs-on: ubuntu-latest
    env:
      ACCOUNTS: ${{ secrets.ACCOUNTS }}
      HOST: ${{ secrets.HOST }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Checkin
        shell: bash
        run: |
          node main.js
